---
title: "Did the pandemic help the enviroment?"
author: "Mariel Ellingsen, Steinar Hansen og Helle Sandsdalen"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction: Provide context and motivation. What questions are being addressed? Why are these questions interesting or important? 
# Begynne med å snakke om innvirkningen av klimakrisa på verden, nevne faktorer som bidrar og at det 
# ikke bare er oppvarming men livskvalitet det går ut over

# Referere til noe statistikk om når det er for sent å snu

# Nevne hvor stor del av flytrafikken som påvirker dette, basert på fakta av andre forskere

# Pandemien har restriktert reising, og har dermed teoretisk påvirket flyreiser.

# Med dette in mind, har luftkvaliteten også kanskje blitt påvirket?

# impact on peoples regular traveling habits, etc, how has this made an impact on the air traffic (?) 

# If there is a notifiable reduction in air traffic, could this be reflected from decreased air pollution (?)
  
# Har pandemien påvirket lufttrafikken, og hvis så, har luftkvaliteten også blitt påvirket?




This journy started with a small question. Did the pandemic help the enviroment? 
And if so, how could we find out?


# Related Work: What other methods have addressed these or similar questions? How do these methods differ from your method?


# Solution/Method: What did you do? What tools and techniques did you use? Was any innovation attempted?


# Data and Experiments: What data did you use? Are your experimental methods reliable? What preprocessing was done on the data?


# Evaluation and Results: Did you properly evaluate your experiments? Did you test for statistical significance? Do your conclusions match your results?


# Writing Quality: Clarity of writing, organization, and grammar.